#pragma once

#define SCREEN_W 80
#define SCREEN_H 64
#define SUBPIXEL_BITS 2
#define ONE_PIXEL (1 << SUBPIXEL_BITS)
#define PLAY_AREA_W (SCREEN_W << SUBPIXEL_BITS)
#define PLAY_AREA_H (SCREEN_H << SUBPIXEL_BITS)
